language: node_js
node_js:
  - 4.4.2
  - 0.12
  - 0.10
  - 0.8
sudo: false
matrix:
  allow_failures:
  - node_js: 4.4.2
  - node_js: 0.12
  - node_js: 0.8
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
   - php5-cli
script:
  - npm run lint || true
  - npm run test
