language: node_js
node_js:
- 4.4.2 # When you update this, also update TRAVIS_NODE_VERSION in travis-deploy to tell who is the deployer build
- 0.12
- 0.1
sudo: false
matrix:
  allow_failures:
  - node_js: 0.1
  - node_js: 0.12

env:
  global:
    - secure: "c4unKozz+OKffwUmypDb+E8qcR9JM7tb7fQ75jidOiz57HM5hmLVJokj017GrUeoPAw3nSE6l0O9Yvyf5K4QNguZ4IXlrtTO1repPLHyUCX3Hoo3PhXDo6g6ySpt8tMpP3dX6r7JUn5YHjxASfOI8VJTmcnxyNkVH66H6VMOA2I="

script:
- npm run lint
- npm run build
- npm run test
- npm run website:install

deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: master
  script: scripts/travis-deploy.sh
